### ISSUE TITLE
Dependency on symfony/http-client 5.4

### ISSUE THREAD

**Issue by fsuter** [raccoondepot/error_log#13]
I just tried installing error_log on a TYPO3 12 install, but I have a conflict around library `symfony/http-client` which is requested in version `^5.4` by error_log.

This is a pretty old version of `symfony/http-client` and, in my case, it is rejected by `symfony/framework-bundle`.

I looked at the (numerous) releases of `symfony/http-client`. I understand that you may have needed an old version to be compatible with TYPO3 11, but with TYPO3 12 requiring PHP 8.1 or more, it should be possible to use `symfony/http-client` in version `^6.4`.

I haven't looked at the code, so I don't know how important the impact could be on your extension, but it could be worth being able to upgrade `symfony/http-client`, since its development is already much further (but requiring PHP 8.2, which would not fit with TYPO3 12 requirements).

**Comment by Voronov** [comment]
@fsuter 
You’re right. We should use symfony/http-client version 6 in TYPO3 12. Please update to the newer version. 
https://github.com/raccoondepot/error_log/releases/tag/12.4.5

Thank you for your participation.

**Comment by fsuter** [comment]
Wow, that was fast! Thanks a lot, it works now.
