### ISSUE TITLE
Fatal error after extension remove

### ISSUE THREAD

**Issue by klinkgmbh** [raccoondepot/error_log#19]
After removing with `composer remove raccoondepot/error-log` following error occurs:

Fatal error: Uncaught Error: Class "RD\ErrorLog\Handler\ErrorHandler" not found in /home/xxxx/public_html/xxxx/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php:2985 Stack trace: #0 /home/xxxx/public_html/xxxx/vendor/typo3/cms-core/Classes/Core/Bootstrap.php(445): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('RD\\ErrorLog\\Han...', 30466) #1 /home/xxxx/public_html/xxxx/vendor/typo3/cms-core/Classes/Core/Bootstrap.php(94): TYPO3\CMS\Core\Core\Bootstrap::initializeErrorHandling() #2 /home/xxxx/public_html/xxxx/public/typo3/index.php(20): TYPO3\CMS\Core\Core\Bootstrap::init(Object(Composer\Autoload\ClassLoader)) #3 /home/xxxx/public_html/xxxx/public/typo3/index.php(21): {closure}() #4 {main} thrown in /home/xxxx/public_html/xxxx/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php on line 2985

TYPO3 12.4.20
PHP 8.1.29

**Comment by Voronov** [comment]
@klinkgmbh You should replace our handlers in the settings file with the original ones.
We will check maybe we can do it on composer remove.

**Comment by klinkgmbh** [comment]
Thanks for the hint, that's it!

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Same errors here. Such fatal errors after deinstalling an extension should definitely be ruled out.
