### ISSUE TITLE
Exception: Container did not exist in LogWriter->writeError

### ISSUE THREAD

**Issue by BenjaminBeck** [raccoondepot/error_log#20]
This happened very early, i think during DI.

GeneralUtility::getContainer() did throw a LogicException.

It was hard to recover from this error.

**Comment by Voronov** [comment]
@BenjaminBeck Which version do you use?

**Comment by BenjaminBeck** [comment]
error_log @ 12.4.6 or maybe 12.4.7
typo3 @ 12.4.20 with php 8.3
in dev env - i might have had a bug in another extension i was working on ..

**Comment by Voronov** [comment]
@BenjaminBeck 
I reviewed your pull request. When we were working on this extension, we encountered a similar error, and simply checking it was sufficient. Honestly, I’m not a fan of this check, but sometimes errors occur before dependency injection. It was working fine on my end. In any case, I don't think that your changes will break anything. I’ve merged them. Thank you for your contribution :)
