### ISSUE TITLE
Exception 1253175643 on every try to open a message

### ISSUE THREAD

**Issue by hirnschmalz** [raccoondepot/error_log#7]
Every time I try to open a log entry I get the error message

```
(1/1) #1253175643 TYPO3\CMS\Extbase\Mvc\Exception\InvalidArgumentTypeException
The argument type for parameter $currentPage of method RD\ErrorLog\Backend\Controller\LogErrorModuleController->viewAction() could not be detected.
```

I'm using the latest TYPO3 v12 with PHP 8.2

**Comment by Voronov** [comment]
@hirnschmalz This issue has been fixed in version 12.4.4. Please update the extension. This version will be available soon. Thank you for your participation!
