### ISSUE TITLE
Unable to open user settings

### ISSUE THREAD

**Issue by hirnschmalz** [raccoondepot/error_log#8]
After installing the extension, I'm no longer able to load the user settings. Try to do so shows an error

```
(1/1) TypeError
htmlspecialchars(): Argument #1 ($string) must be of type string, int given
```

I'm using the latest TYPO3 v12 with PHP 8.2

**Comment by Voronov** [comment]
@hirnschmalz 
This issue is related to a TYPO3 bug. Here is the link for reference: https://forge.typo3.org/issues/104341. I attempted to change the value in TCA to a string, but unfortunately, it did not resolve the issue."

**Comment by bobriusNT** [comment]
@hirnschmalz TYPO3 v.12.4.18 has been released today. It fixes the issue that caused the user settings error. Please update TYPO3 to latest version.
